### ISSUE TITLE
python 3.5?

### ISSUE THREAD

**Issue by ghost** [Malet/zoopla_scraper#1]
@Malet sure you had to use python 3.5

**Comment by Malet** [comment]
Don't have to, but making it compatible with both is tough

**Comment by ghost** [comment]
SSL, giving me a hard time :(, have to install custom python will let you know when I finish

**Comment by ghost** [comment]
ah cool, it works with 3.4, I had to use a dev version of openssl

**Comment by Malet** [comment]
I just used https://github.com/yyuu/pyenv

**Comment by ghost** [comment]
Yeah, what happened was python 3.4 did not have ssl for its version of pip.

Its a long and boring story.
